### ISSUE TITLE
Styles are not being applied to NYTimes.com bits blog

### ISSUE THREAD

**Issue by ftrain** [ftrain/savepublishing#24]
http://bits.blogs.nytimes.com/2012/12/30/f-a-a-rules-make-electronic-devices-on-planes-dangerous/?hp

**Comment by getaaron** [comment]
Possible dupe of https://github.com/ftrain/savepublishing/issues/36

**Comment by ftrain** [comment]
Closed as noted in https://github.com/ftrain/savepublishing/issues/36
