### ISSUE TITLE
UI doesn't appear on http://cityroom.blogs.nytimes.com/

### ISSUE THREAD

**Issue by getaaron** [ftrain/savepublishing#36]
Go to http://cityroom.blogs.nytimes.com/
Run JavaScript

Expected: does stuff
Actual: don't do nothing

**Comment by getaaron** [comment]
Possible dupe of https://github.com/ftrain/savepublishing/issues/24

**Comment by ftrain** [comment]
This seems to be resolved per screenshot below. Feel free to re-open if you don't get similar results.

![Screen Shot 2013-01-04 at 1 02 58 AM](https://f.cloud.github.com/assets/20264/42578/635c995a-5635-11e2-9854-ad6aa71e7ff1.png)
