### ISSUE TITLE
Escaping error: http://www.dadhacker.com/blog/?p=1849

### ISSUE THREAD

**Issue by benzado** [ftrain/savepublishing#44]
A sentence containing "C++" doesn't carry over to Twitter correctly because the plus `+` characters are interpreted as spaces. They should be %-escaped.

**Comment by ftrain** [comment]
Closing with with 886311714ff4ca8e0a2096515fbab2348b7a46c5. Was able to tweet this with plus signs intact and no further problems. Code was calling encodeURI instead of encodeURIcomponent.
